name: Checks

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --check
    - run: cargo clippy --tests --features frivolity -- --deny warnings
    - run: cargo test
